# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.fcyballdisplay.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fcyballdisplay', 'function_path': 'animated_java:fcyballdisplay/variants/default/apply'}
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.hspeed] run function animated_java:fcyballdisplay/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.vspeed] run function animated_java:fcyballdisplay/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.boat] run function animated_java:fcyballdisplay/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.rope_left] run function animated_java:fcyballdisplay/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.rope_right] run function animated_java:fcyballdisplay/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.fcyballdisplay.bone.balloon] run function animated_java:fcyballdisplay/variants/default/zzz/5