# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fcyballdisplay.root] run return 0
execute on passengers if entity @s[tag=aj.fcyballdisplay.data] unless data entity @s {data:{rigHash: '8a4dd803f7b1861ccc411de5be1a863a2bdc56b94f256a66cd470b9682d1a0a4'}} on vehicle run function animated_java:fcyballdisplay/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1