# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fcyballdisplay.root] run return 0
execute on passengers if entity @s[tag=aj.fcyballdisplay.data] unless data entity @s {data:{rigHash: 'd9259567b1f40f385743bec702de52faf720de18e14a507688f2ed6c2ee5c707'}} on vehicle run function animated_java:fcyballdisplay/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1