# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add fcyball.balloon.seat
execute summon minecraft:interaction run function animated_java:fcyball_small_balloon/zzz/13
ride @s mount @n[tag=fcyball.balloon]