# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add fcyball.seat.interaction
data merge entity @s {width:1.6f,height:0.6f,response:true}
ride @s mount @n[tag=fcyball.balloon.seat]