# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fcyballdisplay/animations/sway/zzz/apply_frame {frame: 100}
scoreboard players add @s aj.sway.frame 1