# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fcyball_small_balloon.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:fcyball_small_balloon/as_root/pre_tick
execute if entity @s[tag=aj.fcyball_small_balloon.animation.sway.playing] run function animated_java:fcyball_small_balloon/animations/sway/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
execute unless entity @p[distance=..20] run function animated_java:fcyball_small_balloon/animations/pause_all
execute if entity @p[distance=..15] run function animated_java:fcyball_small_balloon/animations/sway/resume
function #animated_java:fcyball_small_balloon/as_root/post_tick